### ISSUE TITLE
Support GET request for solving 

### ISSUE THREAD

**Issue by sbaer** [mcneel/compute.rhino3d.appserver#38]
Add /solve/{definition} with support for query string inputs for solving

This would let us implement caching headers for browsers as we could return the hash of a definition in an etag
See https://devcenter.heroku.com/articles/increasing-application-performance-with-http-cache-headers

**Comment by fraguada** [comment]
Currently working on this in https://github.com/mcneel/compute.rhino3d.appserver/tree/luis/queryparams
